### ISSUE TITLE
插件依然文章目录不能跳转

### ISSUE THREAD

**Issue by PulSe-kun** [halo-sigs/plugin-bytemd#10]
更新了最新的1.1插件，但是发现目录依然不能正常跳转；
后把旧的删除，重新安装也不能；
![image](https://user-images.githubusercontent.com/66857592/220132450-ef2859f6-85b9-417b-bb64-999009e1bab9.png)

**Comment by ruibaby** [comment]
目前你可能需要清空浏览器缓存才能生效，因为插件的资源（main.js）有设置缓存策略。

详情请看：https://github.com/halo-dev/halo/issues/3205

/kind support

**Comment by PulSe-kun** [comment]
> 目前你可能需要清空浏览器存储才有效，因为插件的资源（main.js）有设置存储策略。
> 
> 详情请看：[halo-dev/halo#3205](https://github.com/halo-dev/halo/issues/3205)
> 
> /亲切的支持

了解了，原来是这样。非常感谢！
