### ISSUE TITLE
带鱼屏情况下，如图，左侧出现一大块空白。

### ISSUE THREAD

**Issue by YuJian95** [halo-sigs/plugin-bytemd#16]
![image](https://user-images.githubusercontent.com/37510077/232283631-28bd25f6-14e4-490c-b479-ca6217ce8eb9.png)

**Comment by ruibaby** [comment]
这应该是一个正常表现，如果屏幕有多宽就显示多宽的话，可能在视觉上会造成一定的困扰，为编辑区域添加一个边距就是为了在编辑和预览的时候方便查看。

/kind support
