### ISSUE TITLE
Task list preview和真正发布的格式不一样

### ISSUE THREAD

**Issue by JCVICTORSUN** [halo-sigs/plugin-bytemd#27]
如图
![image](https://github.com/halo-sigs/plugin-bytemd/assets/53136539/104acd8a-c228-4f38-a912-32f2ef305b04)
![image](https://github.com/halo-sigs/plugin-bytemd/assets/53136539/58418987-dd91-4f0b-903e-81ef3cd95464)

似乎Task list并没有正确被读出来

**Comment by JCVICTORSUN** [comment]
还是说是主题的问题emmmm我是不是应该在主题下面发issue

**Comment by JCVICTORSUN** [comment]
主题是Sakura 2.0.0-beta.2，Halo版本 2.7.0

**Comment by ruibaby** [comment]
我这边好像没有复现：

<img width="868" alt="image" src="https://github.com/halo-sigs/plugin-bytemd/assets/21301288/668693b1-ea5f-4796-b352-30f5d9b26497">
<img width="1082" alt="image" src="https://github.com/halo-sigs/plugin-bytemd/assets/21301288/a3390ffc-7b10-4a5a-8252-5d707c742b58">

**Comment by JCVICTORSUN** [comment]
我这里还是有问题）会和主题适配有关系吗

**Comment by JCVICTORSUN** [comment]
已解决（很早就解决了忘记在这里说了），是格式的问题，在前后需要加空格/回车。
