### ISSUE TITLE
希望能给标题自动加上id

### ISSUE THREAD

**Issue by jiewenhuang** [halo-sigs/plugin-bytemd#31]
生成的h标签没有id，目录容易出错，虽然自己主题自己处理也行，但是感觉还是不太好。

**Comment by gaojie0616** [comment]
自带编辑器的标题是有id的，同求这个功能

**Comment by ruibaby** [comment]
这个功能好像在 https://github.com/halo-sigs/plugin-bytemd/pull/4 中就已经提供了，可以升级到最新版本试试。

<img width="1135" alt="image" src="https://github.com/halo-sigs/plugin-bytemd/assets/21301288/e57684ff-5279-4b1a-8c54-48360548d8a7">

/close

**Comment by jiewenhuang** [comment]
用的一直都是最新版的，1.4.0，并没有这个功能

**Comment by ruibaby** [comment]
> 用的一直都是最新版的，1.4.0，并没有这个功能

那就没能复现这个问题了。

<img width="1668" alt="image" src="https://github.com/halo-sigs/plugin-bytemd/assets/21301288/3c37ac0f-3f11-4111-a18a-7242ade2b0b9">
<img width="1859" alt="image" src="https://github.com/halo-sigs/plugin-bytemd/assets/21301288/29e85816-fb2a-4713-9261-736f791cd656">
<img width="1025" alt="image" src="https://github.com/halo-sigs/plugin-bytemd/assets/21301288/2d13f69b-d60f-47e1-b9b9-58f980ed2142">

/reopen

**Comment by jiewenhuang** [comment]
没事了，瑞士军刀的问题，作者修了。
